BEGIN;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
 "id" SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL UNIQUE,
  shop TEXT,
  name TEXT,
  status BOOLEAN NOT NULL DEFAULT FALSE
);
COMMIT;