name: Create and publish a Docker image

on:
  push:
    branches: ['jelastic']

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      jelastic_env: env-0105831
    secrets: inherit
      