#
name: Create and publish a Docker image

on:
  push:
    branches: ['jelastic']

jobs:
  build-and-push-image:
    env:
      SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: build and deploy
        uses: ./build-and-deploy
        with:
          jelastic_env: env-0105831
        secrets: inherit
      