name: Producer Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_ACCESS_TOKEN: 123
      SHOPIFY_API_KEY: 123
      SHOPIFY_API_SECRET: 123
      HOST: somehost
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Use POSTGRES
        uses: docker://postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
      - run: yarn
      - run: cd web && yarn
      - run: yarn test
